version: 0.2

env:
  variables:
    GLUE_SCRIPT_BUCKET: "glue-job-code-base"
    GLUE_SCRIPT_KEY: "scripts/aggregate_daily_files.py"
    GLUE_JOB_NAME: "food-delivery-data-daily-agg-files"
    GLUE_EXECUTION_ROLE_ARN: "arn:aws:iam::978177281350:role/agg-daily-files-glue-job-role"
    AWS_DEFAULT_REGION: "us-east-2"

phases:
  install:
    commands:
      - 'set -euo pipefail'
      - 'aws --version'
  build:
    commands:
      # Zip and upload Glue script to S3
      - 'echo Uploading script to s3://${GLUE_SCRIPT_BUCKET}/${GLUE_SCRIPT_KEY}'
      - 'aws s3 cp Glue_Job/aggregate_daily_files.py "s3://${GLUE_SCRIPT_BUCKET}/${GLUE_SCRIPT_KEY}"'
      # Zip utilities.py and upload to S3
      - 'cd Glue_Job'
      - 'zip ../utils.zip utilities.py'
      - 'aws s3 cp ../utils.zip "s3://${GLUE_SCRIPT_BUCKET}/${GLUE_SCRIPT_KEY%/*}/utils.zip"'
      - 'cd ..'
  post_build:
    commands:
      - 'echo Updating Glue Job definition ${GLUE_JOB_NAME}'
      - aws glue update-job --region ${AWS_DEFAULT_REGION} --job-name "${GLUE_JOB_NAME}" --job-update "{\"Role\":\"${GLUE_EXECUTION_ROLE_ARN}\",\"GlueVersion\":\"4.0\",\"WorkerType\":\"G.1X\",\"NumberOfWorkers\":10,\"Command\":{\"Name\":\"glueetl\",\"ScriptLocation\":\"s3://${GLUE_SCRIPT_BUCKET}/${GLUE_SCRIPT_KEY}\",\"PythonVersion\":\"3\"},\"DefaultArguments\":{\"--extra-py-files\":\"s3://${GLUE_SCRIPT_BUCKET}/scripts/utils.zip\"},\"ExecutionProperty\":{\"MaxConcurrentRuns\":1}}"

