version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - yum update -y
      - yum install -y zip
      - pip install --upgrade pip

  build:
    commands:
      - set -eux
      - echo "Repo root:" && pwd && ls -la
      - cd "$CODEBUILD_SRC_DIR/Lambda_Functions/Data_Consumer"
      - echo "In Lambda_Functions Lambda_Functions/Data_Consumer:" && pwd && ls -la

      # Check that code file exist
      - test -f data_consumer_sqs_to_S3.py
      # --- STEP 1: Create a temp folder for dependencies and copy funtion code---
      - mkdir -p data_consumer_package_files
      - cp data_consumer_sqs_to_S3.py data_consumer_package_files/

      # --- STEP 2: Zip the dependencies first ---
      - cd data_consumer_package_files
      - zip -r9 ../data_consumer_package.zip .
      - cd ..
      - echo "Package created successfully:" && ls -la data_consumer_package.zip

  post_build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/Lambda_Functions/Data_Consumer"

      - echo "Updating Data Consumer Lambda function code..."
      - aws lambda update-function-code --function-name data_consumer_sqs_to_S3 --zip-file "fileb://data_consumer_package.zip"
      - echo "Data Consumer Lambda function code updated successfully."

      - echo "Waiting for update to complete..."
      - aws lambda wait function-updated --function-name data_consumer_sqs_to_S3

      - echo "Updating Lambda Handler..."
      - aws lambda update-function-configuration --function-name data_consumer_sqs_to_S3 --handler data_consumer_sqs_to_S3.lambda_handler